/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'hello.Debug+V2M-MPS3-SSE-300-FVP' 
 * Target:  'Debug+V2M-MPS3-SSE-300-FVP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE300MPS3.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.5.4 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:USART:CDC@1.10.0 */
#define RTE_Drivers_USART_CDC_ACM       /* Driver USART CDC ACM */
/* Keil::CMSIS Driver:WiFi:ESP8266&UART@1.8.0 */
#define RTE_Drivers_WiFi_ESP8266_UART   /* Driver WiFi ESP8266 (UART) */
/* Keil::Network&MDK-Pro:CORE&IPv4/IPv6 Release@7.19.0 */
#define RTE_Network_Core                /* Network Core */
          #define RTE_Network_IPv4                /* Network IPv4 Stack */
          #define RTE_Network_IPv6                /* Network IPv6 Stack */
          #define RTE_Network_Release             /* Network Release Version */
/* Keil::Network&MDK-Pro:Interface:WiFi@7.19.0 */
#define RTE_Network_Interface_WiFi_0    /* Network Interface WiFi 0 */

/* Keil::Network&MDK-Pro:Service:Web Server Compact&HTTP@7.19.0 */
#define RTE_Network_Web_Server_RO       /* Network Web Server with Read-only Web Resources */
/* Keil::Network&MDK-Pro:Socket:TCP@7.19.0 */
#define RTE_Network_Socket_TCP          /* Network Socket TCP */
/* Keil::Network&MDK-Pro:Socket:UDP@7.19.0 */
#define RTE_Network_Socket_UDP          /* Network Socket UDP */
/* Keil::USB&MDK-Pro:CORE&Release@6.17.0 */
#define RTE_USB_Core                    /* USB Core */
          #define RTE_USB_Core_Release            /* USB Core Release Version */
/* Keil::USB&MDK-Pro:Host:CDC@6.17.0 */
#define RTE_USB_Host_CDC                /* USB Host CDC */


#endif /* RTE_COMPONENTS_H */
